import { getNOVAMarketData } from '../../../lib/blog/marketData';
import MarketPulse from '../MarketPulse';
export const revalidate = 2592000;
export const metadata = {
  title: "Wholesaling Real Estate Laws by State: 2026 Guide",
  description: "Wholesale real estate laws vary significantly by state. This guide covers the key legal requirements, disclosure rules, and assignment regulations across",
  alternates: { canonical: 'https://www.freedealcalc.com/blog/wholesaling-real-estate-by-state' },
};
const s = {page:{maxWidth:760,margin:'0 auto',padding:'80px 24px'},meta:{display:'flex',alignItems:'center',gap:16,marginBottom:32},metaText:{fontFamily:'var(--font-dm-mono, monospace)',fontSize:'0.72rem',color:'#71717a',textTransform:'uppercase',letterSpacing:'0.08em'},dot:{width:3,height:3,background:'#d4d4d8',borderRadius:'50%',display:'inline-block'},h1:{fontFamily:'var(--font-cormorant, Georgia, serif)',fontSize:'clamp(2rem, 4vw, 2.8rem)',fontWeight:700,color:'#18181b',letterSpacing:'-0.02em',lineHeight:1.15,marginBottom:20},intro:{fontFamily:'var(--font-sora, sans-serif)',fontSize:'1.05rem',color:'#3f3f46',lineHeight:1.8,marginBottom:48,padding:'20px 24px',background:'#f4f4f5',borderRadius:8,borderLeft:'3px solid #059669'},h2:{fontFamily:'var(--font-cormorant, Georgia, serif)',fontSize:'clamp(1.4rem, 2.5vw, 1.9rem)',fontWeight:700,color:'#18181b',letterSpacing:'-0.01em',lineHeight:1.2,marginTop:48,marginBottom:16},h3:{fontFamily:'var(--font-sora, sans-serif)',fontSize:'1rem',fontWeight:700,color:'#18181b',marginTop:32,marginBottom:12},p:{fontFamily:'var(--font-sora, sans-serif)',fontSize:'0.975rem',color:'#3f3f46',lineHeight:1.85,marginBottom:20},ul:{fontFamily:'var(--font-sora, sans-serif)',fontSize:'0.975rem',color:'#3f3f46',lineHeight:1.85,marginBottom:20,paddingLeft:24},li:{marginBottom:8},cta:{background:'linear-gradient(135deg, #059669, #047857)',borderRadius:12,padding:'36px 40px',margin:'48px 0',color:'#ffffff'},ctaTitle:{fontFamily:'var(--font-cormorant, Georgia, serif)',fontSize:'1.5rem',fontWeight:700,marginBottom:10,lineHeight:1.2},ctaText:{fontFamily:'var(--font-sora, sans-serif)',fontSize:'0.95rem',color:'rgba(255,255,255,0.85)',lineHeight:1.7,marginBottom:20},ctaBtn:{display:'inline-block',background:'#ffffff',color:'#059669',padding:'12px 24px',borderRadius:6,fontFamily:'var(--font-sora, sans-serif)',fontWeight:700,fontSize:'0.9rem',textDecoration:'none'},divider:{height:1,background:'#e4e4e7',margin:'40px 0'},byline:{fontFamily:'var(--font-sora, sans-serif)',fontSize:'0.85rem',color:'#71717a',lineHeight:1.7,marginTop:48,padding:'24px 0',borderTop:'1px solid #e4e4e7'},formula:{background:'#0f172a',borderRadius:10,padding:'24px 28px',margin:'24px 0',textAlign:'center'},formulaText:{fontFamily:'var(--font-cormorant, Georgia, serif)',fontSize:'clamp(1.2rem, 2.5vw, 1.6rem)',color:'#34d399',fontWeight:700},table:{width:'100%',borderCollapse:'collapse',margin:'24px 0'},th:{background:'#f4f4f5',padding:'10px 14px',textAlign:'left',fontFamily:'var(--font-sora, sans-serif)',fontSize:'0.85rem',fontWeight:700,color:'#18181b',borderBottom:'2px solid #e4e4e7'},td:{padding:'10px 14px',fontFamily:'var(--font-sora, sans-serif)',fontSize:'0.875rem',color:'#3f3f46',borderBottom:'1px solid #f4f4f5'}};
const TopCTA = () => (<div style={s.cta}><div style={s.ctaTitle}>Run any deal through Freddie — free analysis in 60 seconds.</div><div style={s.ctaText}>Flip, rental, BRRRR, or wholesale — Freddie handles all four strategies for any address.</div><a href="https://www.freedealcalc.com" style={s.ctaBtn}>Try Freddie Free</a></div>);
export default async function Page() {
  const market = await getNOVAMarketData();
  return (
    <div style={s.page}>
      <div style={s.meta}><span style={s.metaText}>Wholesale Legal</span><span style={s.dot}/><span style={s.metaText}>2026</span></div>
      <h1 style={s.h1}>Wholesaling Real Estate Laws by State: A 2026 Guide</h1>
      <p style={s.intro}>Wholesaling real estate is legal in all 50 states — but the rules differ meaningfully by state. Some states require a real estate license for wholesale activity at certain volumes. Others require specific disclosures to sellers. Understanding your state's rules before you start is non-negotiable. This guide covers the key states with the most active wholesale markets.</p>
      <TopCTA />
      <h2 style={s.h2}>The Core Legal Question in Wholesaling</h2>
      <p style={s.p}>The central legal question in wholesaling is whether assigning a contract constitutes acting as a real estate broker without a license. Most states have concluded that a wholesaler who is a principal in the transaction (has a contract to purchase) is not acting as an agent and therefore doesn't need a license. The line gets blurry when marketing a property you don't yet own or conducting activities that look more like brokerage than purchasing.</p>
      <h2 style={s.h2}>States with Notable Wholesale Regulations</h2>
      <table style={s.table}><thead><tr><th style={s.th}>State</th><th style={s.th}>Assignment Disclosure</th><th style={s.th}>License Required?</th><th style={s.th}>Notes</th></tr></thead><tbody><tr><td style={s.td}>Texas</td><td style={s.td}>No specific law</td><td style={s.td}>Generally no</td><td style={s.td}>Texas requires disclosure of investor intent in some situations. Consult an attorney for high-volume operations</td></tr><tr><td style={s.td}>Florida</td><td style={s.td}>Yes (2022 law)</td><td style={s.td}>No</td><td style={s.td}>Must disclose intent to assign to seller. Double-close is common workaround</td></tr><tr><td style={s.td}>Illinois</td><td style={s.td}>No specific law</td><td style={s.td}>Generally no</td><td style={s.td}>Cook County (Chicago) has been scrutinizing wholesale activity more closely</td></tr><tr><td style={s.td}>California</td><td style={s.td}>No specific law</td><td style={s.td}>Generally no</td><td style={s.td}>Some California cities have been considering wholesale regulations</td></tr><tr><td style={s.td}>Georgia</td><td style={s.td}>No specific law</td><td style={s.td}>Generally no</td><td style={s.td}>Atlanta has a very active wholesale market with few restrictions</td></tr><tr><td style={s.td}>Ohio</td><td style={s.td}>No specific law</td><td style={s.td}>Generally no</td><td style={s.td}>High-volume wholesale market across Columbus, Cleveland, Cincinnati</td></tr></tbody></table>
      <h2 style={s.h2}>Best Practices Regardless of State</h2>
      <ul style={s.ul}>
        <li style={s.li}>Always use a written purchase contract — never a 'verbal agreement' or letter of intent without contract</li>
        <li style={s.li}>Clearly disclose your investor status to sellers — never misrepresent your intentions</li>
        <li style={s.li}>Use proper assignment of contract language reviewed by a real estate attorney in your state</li>
        <li style={s.li}>Maintain records of all transactions for compliance purposes</li>
        <li style={s.li}>If you're doing high volume (20+ assignments per year), consult a real estate attorney about licensing requirements</li>
      </ul>
      <h2 style={s.h2}>The Double-Close Alternative</h2>
      <p style={s.p}>When assignment fees are very large or sellers are uncomfortable with assignment, a double-close (simultaneous close) may be used. You close on the purchase and then immediately close the resale on the same day. This requires transactional funding — short-term bridge money that funds your purchase for hours until the resale closes. Transactional funding companies charge 1–2% of the purchase price for this service.</p>
      <div style={s.cta}><div style={s.ctaTitle}>Calculate Your Wholesale MAO Free for Any State</div><div style={s.ctaText}>Freddie gives you ARV and MAO for any address in any state — free, instant, no account needed.</div><a href="https://www.freedealcalc.com" style={s.ctaBtn}>Run My Wholesale Numbers</a></div>
      <div style={s.divider}/>
      <p style={s.byline}><strong>Dan White</strong> is a licensed Virginia real estate agent at Pearson Smith Realty and founder of <a href="https://www.freedealcalc.com" style={{color:'#059669'}}>FreeDealCalc.com</a>. He has been investing in Northern Virginia real estate for 20+ years.</p>
    </div>
  );
}
